name: Build and Publish Version Tags

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version tag
        id: version
        run: echo "VERSION=$(echo ${{ github.ref }} | sed -e 's,.*/v,,')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: openstad/image:${{ env.VERSION }}

      - name: Output image digest
        run: echo "Image digest ${{ steps.buildx.outputs.digest }}"
